package com.online.taxi.request;

import com.online.taxi.entity.Order;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.math.BigDecimal;
import java.util.Date;

/**
 * 功能描述
 * @date 2018/8/27
 */
@Data
@EqualsAndHashCode(callSuper=false)
public class OrderDtoRequest extends Order {
    private Integer orderId;

    private String orderPrice;
    /**
     * 城市编码
     */
    private String cityCode;
    private String cityName;

    private Integer serviceTypeId;
    private String serviceTypeName;

    private Integer channelId;
    private String channelName;

    private Integer carLevelId;
    private String carLevelName;

    /**
     * 用车时长
     */
    private Integer useCarTime;

    /**
     * 过路费
     */
    private BigDecimal roadPrice;
    /**
     * 停车费
     */
    private BigDecimal parkingPrice;
    /**
     * 其它费用
     */
    private BigDecimal otherPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_reassignment_record.driver_id_now
     *
     * @mbggenerated
     */
    private Integer driverIdNow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_reassignment_record.operator
     *
     * @mbggenerated
     * 操作者
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_reassignment_record.reason_type
     *
     * @mbggenerated
     * 改派类型
     */
    private Integer reasonType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_order_reassignment_record.reason_text
     *
     * @mbggenerated
     * 改派内容
     */
    private String reasonText;

    /**
     * 订单ids
     */
    private String orderIds;

    private Integer updateType;
    /**
     * 司机经度
     */
    private String driverLongitude;
    /**
     * 司机纬度
     */
    private String driverLatitude;

}
