package com.online.taxi.mapper;

import com.online.taxi.entity.Order;
import com.online.taxi.request.OrderDtoRequest;

import org.springframework.stereotype.Service;

import java.util.Map;
/**
 * 功能描述
 * @date 2018/8/25
 */
@Service
public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbggenerated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbggenerated
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbggenerated
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderDtoRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order
     *
     * @mbggenerated
     */
    int batchUpdate(Map<String, Object> map);

}
