package com.online.taxi.mapper;

import com.online.taxi.entity.ServiceType;
import org.springframework.stereotype.Service;

/**
 * 功能描述
 * @date 2018/8/25
 */
@Service
public interface ServiceTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_service_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_service_type
     *
     * @mbggenerated
     */
    int insert(ServiceType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_service_type
     *
     * @mbggenerated
     */
    int insertSelective(ServiceType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_service_type
     *
     * @mbggenerated
     */
    ServiceType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_service_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ServiceType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_service_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ServiceType record);
}
