package com.online.taxi.mapper;

import com.online.taxi.entity.CallRecords;
import org.springframework.stereotype.Service;

@Service
public interface CallRecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_call_records
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_call_records
     *
     * @mbggenerated
     */
    int insert(CallRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_call_records
     *
     * @mbggenerated
     */
    int insertSelective(CallRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_call_records
     *
     * @mbggenerated
     */
    CallRecords selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_call_records
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CallRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_call_records
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CallRecords record);
}
