package com.online.taxi.mapper;

import com.online.taxi.entity.SecretVoiceRecords;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public interface SecretVoiceRecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_secret_voice_records
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_secret_voice_records
     *
     * @mbggenerated
     */
    int insert(SecretVoiceRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_secret_voice_records
     *
     * @mbggenerated
     */
    int insertSelective(SecretVoiceRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_secret_voice_records
     *
     * @mbggenerated
     */
    SecretVoiceRecords selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_secret_voice_records
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SecretVoiceRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_secret_voice_records
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SecretVoiceRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_secret_voice_records
     *
     * @mbggenerated
     */
    List<SecretVoiceRecords> selectRecordsUrlIsNull();
}
