package com.online.taxi.mapper;

import com.online.taxi.entity.AlipayCallbackInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface AlipayCallbackInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_alipay_callback_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_alipay_callback_info
     *
     * @mbggenerated
     */
    int insert(AlipayCallbackInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_alipay_callback_info
     *
     * @mbggenerated
     */
    int insertSelective(AlipayCallbackInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_alipay_callback_info
     *
     * @mbggenerated
     */
    AlipayCallbackInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_alipay_callback_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AlipayCallbackInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_alipay_callback_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AlipayCallbackInfo record);
}