package com.online.taxi.mapper;

import com.online.taxi.entity.WeixinpayCallbackInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface WeixinpayCallbackInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_weixinpay_callback_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_weixinpay_callback_info
     *
     * @mbggenerated
     */
    int insert(WeixinpayCallbackInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_weixinpay_callback_info
     *
     * @mbggenerated
     */
    int insertSelective(WeixinpayCallbackInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_weixinpay_callback_info
     *
     * @mbggenerated
     */
    WeixinpayCallbackInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_weixinpay_callback_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WeixinpayCallbackInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_weixinpay_callback_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WeixinpayCallbackInfo record);
}