package com.online.taxi.mapper;

import com.online.taxi.entity.DriverOrderMessageStatistical;

public interface DriverOrderMessageStatisticalMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_driver_order_message_statistical
     *
     * @mbggenerated
     */
    int insertSelective(DriverOrderMessageStatistical record);


    DriverOrderMessageStatistical selectByPrimaryKey(Integer id);

}
