package com.online.taxi.mapper;

import com.online.taxi.entity.MessageShow;

public interface MessageShowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_message_show
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_message_show
     *
     * @mbggenerated
     */
    int insert(MessageShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_message_show
     *
     * @mbggenerated
     */
    int insertSelective(MessageShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_message_show
     *
     * @mbggenerated
     */
    MessageShow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_message_show
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MessageShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_message_show
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MessageShow record);
}