package com.online.taxi.entity;

import java.util.Date;

public class AlipayCallbackInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.notify_time
     *
     * @mbggenerated
     */
    private String notifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.notify_type
     *
     * @mbggenerated
     */
    private String notifyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.notify_id
     *
     * @mbggenerated
     */
    private String notifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.app_id
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.charset
     *
     * @mbggenerated
     */
    private String charset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.sign_type
     *
     * @mbggenerated
     */
    private String signType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.sign
     *
     * @mbggenerated
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.trade_no
     *
     * @mbggenerated
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.out_trade_no
     *
     * @mbggenerated
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.out_biz_no
     *
     * @mbggenerated
     */
    private String outBizNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.buyer_id
     *
     * @mbggenerated
     */
    private String buyerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.buyer_logon_id
     *
     * @mbggenerated
     */
    private String buyerLogonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.seller_id
     *
     * @mbggenerated
     */
    private String sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.seller_email
     *
     * @mbggenerated
     */
    private String sellerEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.trade_status
     *
     * @mbggenerated
     */
    private String tradeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.total_amount
     *
     * @mbggenerated
     */
    private String totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.receipt_amount
     *
     * @mbggenerated
     */
    private String receiptAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.invoice_amount
     *
     * @mbggenerated
     */
    private String invoiceAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.buyer_pay_amount
     *
     * @mbggenerated
     */
    private String buyerPayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.point_amount
     *
     * @mbggenerated
     */
    private String pointAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.refund_fee
     *
     * @mbggenerated
     */
    private String refundFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.subject
     *
     * @mbggenerated
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.body
     *
     * @mbggenerated
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.gmt_create
     *
     * @mbggenerated
     */
    private String gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.gmt_payment
     *
     * @mbggenerated
     */
    private String gmtPayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.gmt_refund
     *
     * @mbggenerated
     */
    private String gmtRefund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.gmt_close
     *
     * @mbggenerated
     */
    private String gmtClose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.fund_bill_list
     *
     * @mbggenerated
     */
    private String fundBillList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.passback_params
     *
     * @mbggenerated
     */
    private String passbackParams;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.voucher_detail_list
     *
     * @mbggenerated
     */
    private String voucherDetailList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_alipay_callback_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.id
     *
     * @return the value of tbl_alipay_callback_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.id
     *
     * @param id the value for tbl_alipay_callback_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.notify_time
     *
     * @return the value of tbl_alipay_callback_info.notify_time
     *
     * @mbggenerated
     */
    public String getNotifyTime() {
        return notifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.notify_time
     *
     * @param notifyTime the value for tbl_alipay_callback_info.notify_time
     *
     * @mbggenerated
     */
    public void setNotifyTime(String notifyTime) {
        this.notifyTime = notifyTime == null ? null : notifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.notify_type
     *
     * @return the value of tbl_alipay_callback_info.notify_type
     *
     * @mbggenerated
     */
    public String getNotifyType() {
        return notifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.notify_type
     *
     * @param notifyType the value for tbl_alipay_callback_info.notify_type
     *
     * @mbggenerated
     */
    public void setNotifyType(String notifyType) {
        this.notifyType = notifyType == null ? null : notifyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.notify_id
     *
     * @return the value of tbl_alipay_callback_info.notify_id
     *
     * @mbggenerated
     */
    public String getNotifyId() {
        return notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.notify_id
     *
     * @param notifyId the value for tbl_alipay_callback_info.notify_id
     *
     * @mbggenerated
     */
    public void setNotifyId(String notifyId) {
        this.notifyId = notifyId == null ? null : notifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.app_id
     *
     * @return the value of tbl_alipay_callback_info.app_id
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.app_id
     *
     * @param appId the value for tbl_alipay_callback_info.app_id
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.charset
     *
     * @return the value of tbl_alipay_callback_info.charset
     *
     * @mbggenerated
     */
    public String getCharset() {
        return charset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.charset
     *
     * @param charset the value for tbl_alipay_callback_info.charset
     *
     * @mbggenerated
     */
    public void setCharset(String charset) {
        this.charset = charset == null ? null : charset.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.version
     *
     * @return the value of tbl_alipay_callback_info.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.version
     *
     * @param version the value for tbl_alipay_callback_info.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.sign_type
     *
     * @return the value of tbl_alipay_callback_info.sign_type
     *
     * @mbggenerated
     */
    public String getSignType() {
        return signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.sign_type
     *
     * @param signType the value for tbl_alipay_callback_info.sign_type
     *
     * @mbggenerated
     */
    public void setSignType(String signType) {
        this.signType = signType == null ? null : signType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.sign
     *
     * @return the value of tbl_alipay_callback_info.sign
     *
     * @mbggenerated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.sign
     *
     * @param sign the value for tbl_alipay_callback_info.sign
     *
     * @mbggenerated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.trade_no
     *
     * @return the value of tbl_alipay_callback_info.trade_no
     *
     * @mbggenerated
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.trade_no
     *
     * @param tradeNo the value for tbl_alipay_callback_info.trade_no
     *
     * @mbggenerated
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.out_trade_no
     *
     * @return the value of tbl_alipay_callback_info.out_trade_no
     *
     * @mbggenerated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.out_trade_no
     *
     * @param outTradeNo the value for tbl_alipay_callback_info.out_trade_no
     *
     * @mbggenerated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.out_biz_no
     *
     * @return the value of tbl_alipay_callback_info.out_biz_no
     *
     * @mbggenerated
     */
    public String getOutBizNo() {
        return outBizNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.out_biz_no
     *
     * @param outBizNo the value for tbl_alipay_callback_info.out_biz_no
     *
     * @mbggenerated
     */
    public void setOutBizNo(String outBizNo) {
        this.outBizNo = outBizNo == null ? null : outBizNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.buyer_id
     *
     * @return the value of tbl_alipay_callback_info.buyer_id
     *
     * @mbggenerated
     */
    public String getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.buyer_id
     *
     * @param buyerId the value for tbl_alipay_callback_info.buyer_id
     *
     * @mbggenerated
     */
    public void setBuyerId(String buyerId) {
        this.buyerId = buyerId == null ? null : buyerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.buyer_logon_id
     *
     * @return the value of tbl_alipay_callback_info.buyer_logon_id
     *
     * @mbggenerated
     */
    public String getBuyerLogonId() {
        return buyerLogonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.buyer_logon_id
     *
     * @param buyerLogonId the value for tbl_alipay_callback_info.buyer_logon_id
     *
     * @mbggenerated
     */
    public void setBuyerLogonId(String buyerLogonId) {
        this.buyerLogonId = buyerLogonId == null ? null : buyerLogonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.seller_id
     *
     * @return the value of tbl_alipay_callback_info.seller_id
     *
     * @mbggenerated
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.seller_id
     *
     * @param sellerId the value for tbl_alipay_callback_info.seller_id
     *
     * @mbggenerated
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId == null ? null : sellerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.seller_email
     *
     * @return the value of tbl_alipay_callback_info.seller_email
     *
     * @mbggenerated
     */
    public String getSellerEmail() {
        return sellerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.seller_email
     *
     * @param sellerEmail the value for tbl_alipay_callback_info.seller_email
     *
     * @mbggenerated
     */
    public void setSellerEmail(String sellerEmail) {
        this.sellerEmail = sellerEmail == null ? null : sellerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.trade_status
     *
     * @return the value of tbl_alipay_callback_info.trade_status
     *
     * @mbggenerated
     */
    public String getTradeStatus() {
        return tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.trade_status
     *
     * @param tradeStatus the value for tbl_alipay_callback_info.trade_status
     *
     * @mbggenerated
     */
    public void setTradeStatus(String tradeStatus) {
        this.tradeStatus = tradeStatus == null ? null : tradeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.total_amount
     *
     * @return the value of tbl_alipay_callback_info.total_amount
     *
     * @mbggenerated
     */
    public String getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.total_amount
     *
     * @param totalAmount the value for tbl_alipay_callback_info.total_amount
     *
     * @mbggenerated
     */
    public void setTotalAmount(String totalAmount) {
        this.totalAmount = totalAmount == null ? null : totalAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.receipt_amount
     *
     * @return the value of tbl_alipay_callback_info.receipt_amount
     *
     * @mbggenerated
     */
    public String getReceiptAmount() {
        return receiptAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.receipt_amount
     *
     * @param receiptAmount the value for tbl_alipay_callback_info.receipt_amount
     *
     * @mbggenerated
     */
    public void setReceiptAmount(String receiptAmount) {
        this.receiptAmount = receiptAmount == null ? null : receiptAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.invoice_amount
     *
     * @return the value of tbl_alipay_callback_info.invoice_amount
     *
     * @mbggenerated
     */
    public String getInvoiceAmount() {
        return invoiceAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.invoice_amount
     *
     * @param invoiceAmount the value for tbl_alipay_callback_info.invoice_amount
     *
     * @mbggenerated
     */
    public void setInvoiceAmount(String invoiceAmount) {
        this.invoiceAmount = invoiceAmount == null ? null : invoiceAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.buyer_pay_amount
     *
     * @return the value of tbl_alipay_callback_info.buyer_pay_amount
     *
     * @mbggenerated
     */
    public String getBuyerPayAmount() {
        return buyerPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.buyer_pay_amount
     *
     * @param buyerPayAmount the value for tbl_alipay_callback_info.buyer_pay_amount
     *
     * @mbggenerated
     */
    public void setBuyerPayAmount(String buyerPayAmount) {
        this.buyerPayAmount = buyerPayAmount == null ? null : buyerPayAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.point_amount
     *
     * @return the value of tbl_alipay_callback_info.point_amount
     *
     * @mbggenerated
     */
    public String getPointAmount() {
        return pointAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.point_amount
     *
     * @param pointAmount the value for tbl_alipay_callback_info.point_amount
     *
     * @mbggenerated
     */
    public void setPointAmount(String pointAmount) {
        this.pointAmount = pointAmount == null ? null : pointAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.refund_fee
     *
     * @return the value of tbl_alipay_callback_info.refund_fee
     *
     * @mbggenerated
     */
    public String getRefundFee() {
        return refundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.refund_fee
     *
     * @param refundFee the value for tbl_alipay_callback_info.refund_fee
     *
     * @mbggenerated
     */
    public void setRefundFee(String refundFee) {
        this.refundFee = refundFee == null ? null : refundFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.subject
     *
     * @return the value of tbl_alipay_callback_info.subject
     *
     * @mbggenerated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.subject
     *
     * @param subject the value for tbl_alipay_callback_info.subject
     *
     * @mbggenerated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.body
     *
     * @return the value of tbl_alipay_callback_info.body
     *
     * @mbggenerated
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.body
     *
     * @param body the value for tbl_alipay_callback_info.body
     *
     * @mbggenerated
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.gmt_create
     *
     * @return the value of tbl_alipay_callback_info.gmt_create
     *
     * @mbggenerated
     */
    public String getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.gmt_create
     *
     * @param gmtCreate the value for tbl_alipay_callback_info.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(String gmtCreate) {
        this.gmtCreate = gmtCreate == null ? null : gmtCreate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.gmt_payment
     *
     * @return the value of tbl_alipay_callback_info.gmt_payment
     *
     * @mbggenerated
     */
    public String getGmtPayment() {
        return gmtPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.gmt_payment
     *
     * @param gmtPayment the value for tbl_alipay_callback_info.gmt_payment
     *
     * @mbggenerated
     */
    public void setGmtPayment(String gmtPayment) {
        this.gmtPayment = gmtPayment == null ? null : gmtPayment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.gmt_refund
     *
     * @return the value of tbl_alipay_callback_info.gmt_refund
     *
     * @mbggenerated
     */
    public String getGmtRefund() {
        return gmtRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.gmt_refund
     *
     * @param gmtRefund the value for tbl_alipay_callback_info.gmt_refund
     *
     * @mbggenerated
     */
    public void setGmtRefund(String gmtRefund) {
        this.gmtRefund = gmtRefund == null ? null : gmtRefund.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.gmt_close
     *
     * @return the value of tbl_alipay_callback_info.gmt_close
     *
     * @mbggenerated
     */
    public String getGmtClose() {
        return gmtClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.gmt_close
     *
     * @param gmtClose the value for tbl_alipay_callback_info.gmt_close
     *
     * @mbggenerated
     */
    public void setGmtClose(String gmtClose) {
        this.gmtClose = gmtClose == null ? null : gmtClose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.fund_bill_list
     *
     * @return the value of tbl_alipay_callback_info.fund_bill_list
     *
     * @mbggenerated
     */
    public String getFundBillList() {
        return fundBillList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.fund_bill_list
     *
     * @param fundBillList the value for tbl_alipay_callback_info.fund_bill_list
     *
     * @mbggenerated
     */
    public void setFundBillList(String fundBillList) {
        this.fundBillList = fundBillList == null ? null : fundBillList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.passback_params
     *
     * @return the value of tbl_alipay_callback_info.passback_params
     *
     * @mbggenerated
     */
    public String getPassbackParams() {
        return passbackParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.passback_params
     *
     * @param passbackParams the value for tbl_alipay_callback_info.passback_params
     *
     * @mbggenerated
     */
    public void setPassbackParams(String passbackParams) {
        this.passbackParams = passbackParams == null ? null : passbackParams.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.voucher_detail_list
     *
     * @return the value of tbl_alipay_callback_info.voucher_detail_list
     *
     * @mbggenerated
     */
    public String getVoucherDetailList() {
        return voucherDetailList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.voucher_detail_list
     *
     * @param voucherDetailList the value for tbl_alipay_callback_info.voucher_detail_list
     *
     * @mbggenerated
     */
    public void setVoucherDetailList(String voucherDetailList) {
        this.voucherDetailList = voucherDetailList == null ? null : voucherDetailList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.create_time
     *
     * @return the value of tbl_alipay_callback_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.create_time
     *
     * @param createTime the value for tbl_alipay_callback_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_alipay_callback_info.update_time
     *
     * @return the value of tbl_alipay_callback_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_alipay_callback_info.update_time
     *
     * @param updateTime the value for tbl_alipay_callback_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}