package com.online.taxi.entity;

import java.util.Date;

public class WeixinpayCallbackInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_weixinpay_callback_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_weixinpay_callback_info.transaction_id
     *
     * @mbggenerated
     */
    private String transactionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_weixinpay_callback_info.out_trade_no
     *
     * @mbggenerated
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_weixinpay_callback_info.total_fee
     *
     * @mbggenerated
     */
    private Integer totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_weixinpay_callback_info.body
     *
     * @mbggenerated
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_weixinpay_callback_info.result_code
     *
     * @mbggenerated
     */
    private String resultCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_weixinpay_callback_info.err_code
     *
     * @mbggenerated
     */
    private String errCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_weixinpay_callback_info.openid
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_weixinpay_callback_info.trade_type
     *
     * @mbggenerated
     */
    private String tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_weixinpay_callback_info.bank_type
     *
     * @mbggenerated
     */
    private String bankType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_weixinpay_callback_info.time_end
     *
     * @mbggenerated
     */
    private Date timeEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_weixinpay_callback_info.attach
     *
     * @mbggenerated
     */
    private String attach;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_weixinpay_callback_info.order_type
     *
     * @mbggenerated
     */
    private Integer orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_weixinpay_callback_info.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_weixinpay_callback_info.mch_id
     *
     * @mbggenerated
     */
    private String mchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_weixinpay_callback_info.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_weixinpay_callback_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_weixinpay_callback_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_weixinpay_callback_info.id
     *
     * @return the value of tbl_weixinpay_callback_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_weixinpay_callback_info.id
     *
     * @param id the value for tbl_weixinpay_callback_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_weixinpay_callback_info.transaction_id
     *
     * @return the value of tbl_weixinpay_callback_info.transaction_id
     *
     * @mbggenerated
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_weixinpay_callback_info.transaction_id
     *
     * @param transactionId the value for tbl_weixinpay_callback_info.transaction_id
     *
     * @mbggenerated
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_weixinpay_callback_info.out_trade_no
     *
     * @return the value of tbl_weixinpay_callback_info.out_trade_no
     *
     * @mbggenerated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_weixinpay_callback_info.out_trade_no
     *
     * @param outTradeNo the value for tbl_weixinpay_callback_info.out_trade_no
     *
     * @mbggenerated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_weixinpay_callback_info.total_fee
     *
     * @return the value of tbl_weixinpay_callback_info.total_fee
     *
     * @mbggenerated
     */
    public Integer getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_weixinpay_callback_info.total_fee
     *
     * @param totalFee the value for tbl_weixinpay_callback_info.total_fee
     *
     * @mbggenerated
     */
    public void setTotalFee(Integer totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_weixinpay_callback_info.body
     *
     * @return the value of tbl_weixinpay_callback_info.body
     *
     * @mbggenerated
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_weixinpay_callback_info.body
     *
     * @param body the value for tbl_weixinpay_callback_info.body
     *
     * @mbggenerated
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_weixinpay_callback_info.result_code
     *
     * @return the value of tbl_weixinpay_callback_info.result_code
     *
     * @mbggenerated
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_weixinpay_callback_info.result_code
     *
     * @param resultCode the value for tbl_weixinpay_callback_info.result_code
     *
     * @mbggenerated
     */
    public void setResultCode(String resultCode) {
        this.resultCode = resultCode == null ? null : resultCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_weixinpay_callback_info.err_code
     *
     * @return the value of tbl_weixinpay_callback_info.err_code
     *
     * @mbggenerated
     */
    public String getErrCode() {
        return errCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_weixinpay_callback_info.err_code
     *
     * @param errCode the value for tbl_weixinpay_callback_info.err_code
     *
     * @mbggenerated
     */
    public void setErrCode(String errCode) {
        this.errCode = errCode == null ? null : errCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_weixinpay_callback_info.openid
     *
     * @return the value of tbl_weixinpay_callback_info.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_weixinpay_callback_info.openid
     *
     * @param openid the value for tbl_weixinpay_callback_info.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_weixinpay_callback_info.trade_type
     *
     * @return the value of tbl_weixinpay_callback_info.trade_type
     *
     * @mbggenerated
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_weixinpay_callback_info.trade_type
     *
     * @param tradeType the value for tbl_weixinpay_callback_info.trade_type
     *
     * @mbggenerated
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_weixinpay_callback_info.bank_type
     *
     * @return the value of tbl_weixinpay_callback_info.bank_type
     *
     * @mbggenerated
     */
    public String getBankType() {
        return bankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_weixinpay_callback_info.bank_type
     *
     * @param bankType the value for tbl_weixinpay_callback_info.bank_type
     *
     * @mbggenerated
     */
    public void setBankType(String bankType) {
        this.bankType = bankType == null ? null : bankType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_weixinpay_callback_info.time_end
     *
     * @return the value of tbl_weixinpay_callback_info.time_end
     *
     * @mbggenerated
     */
    public Date getTimeEnd() {
        return timeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_weixinpay_callback_info.time_end
     *
     * @param timeEnd the value for tbl_weixinpay_callback_info.time_end
     *
     * @mbggenerated
     */
    public void setTimeEnd(Date timeEnd) {
        this.timeEnd = timeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_weixinpay_callback_info.attach
     *
     * @return the value of tbl_weixinpay_callback_info.attach
     *
     * @mbggenerated
     */
    public String getAttach() {
        return attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_weixinpay_callback_info.attach
     *
     * @param attach the value for tbl_weixinpay_callback_info.attach
     *
     * @mbggenerated
     */
    public void setAttach(String attach) {
        this.attach = attach == null ? null : attach.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_weixinpay_callback_info.order_type
     *
     * @return the value of tbl_weixinpay_callback_info.order_type
     *
     * @mbggenerated
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_weixinpay_callback_info.order_type
     *
     * @param orderType the value for tbl_weixinpay_callback_info.order_type
     *
     * @mbggenerated
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_weixinpay_callback_info.status
     *
     * @return the value of tbl_weixinpay_callback_info.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_weixinpay_callback_info.status
     *
     * @param status the value for tbl_weixinpay_callback_info.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_weixinpay_callback_info.mch_id
     *
     * @return the value of tbl_weixinpay_callback_info.mch_id
     *
     * @mbggenerated
     */
    public String getMchId() {
        return mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_weixinpay_callback_info.mch_id
     *
     * @param mchId the value for tbl_weixinpay_callback_info.mch_id
     *
     * @mbggenerated
     */
    public void setMchId(String mchId) {
        this.mchId = mchId == null ? null : mchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_weixinpay_callback_info.source
     *
     * @return the value of tbl_weixinpay_callback_info.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_weixinpay_callback_info.source
     *
     * @param source the value for tbl_weixinpay_callback_info.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_weixinpay_callback_info.create_time
     *
     * @return the value of tbl_weixinpay_callback_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_weixinpay_callback_info.create_time
     *
     * @param createTime the value for tbl_weixinpay_callback_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_weixinpay_callback_info.update_time
     *
     * @return the value of tbl_weixinpay_callback_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_weixinpay_callback_info.update_time
     *
     * @param updateTime the value for tbl_weixinpay_callback_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}